# Generated by Django 4.1.7 on 2024-01-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.JSONField()),
                ('email', models.EmailField(max_length=254)),
                ('project_manager', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='PoolTestEnvironment.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_id', models.CharField(max_length=50)),
                ('fqdn', models.CharField(default='', max_length=100)),
                ('eic_version', models.CharField(default='', max_length=50)),
                ('booking_start_date', models.DateField()),
                ('booking_end_date', models.DateField()),
                ('app_set', models.CharField(max_length=100)),
                ('namespace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='PoolTestEnvironment.namespace')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='PoolTestEnvironment.team')),
            ],
        ),
    ]
