# Generated by Django 4.1.7 on 2024-01-29 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PoolTestEnvironment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='namespace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='PoolTestEnvironment.namespace'),
        ),
    ]
