# Generated by Django 4.1.7 on 2024-01-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoolTestEnvironment', '0002_alter_booking_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tls_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
