# Generated by Django 4.1.7 on 2024-02-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoolTestEnvironment', '0003_booking_tls_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpu_required', models.IntegerField(default=0)),
                ('memory_required', models.IntegerField(default=0)),
            ],
        ),
    ]
