# Generated by Django 4.1.7 on 2024-03-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoolTestEnvironment', '0004_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
