# Generated by Django 4.1.7 on 2024-03-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoolTestEnvironment', '0005_booking_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='fqdn',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ip',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='cpu_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='memory_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cluster',
            name='cpu_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cluster',
            name='memory_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='namespace',
            name='fqdn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='namespace',
            name='ip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
