# Generated by Django 4.1.7 on 2023-10-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EICRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EORole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eicuserprofile',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='eouserprofile',
            name='schema',
        ),
        migrations.AddField(
            model_name='eicuserprofile',
            name='schema',
            field=models.ManyToManyField(to='manager.eicrole'),
        ),
        migrations.AddField(
            model_name='eouserprofile',
            name='schema',
            field=models.ManyToManyField(to='manager.eorole'),
        ),
    ]
