# Generated by Django 4.1.7 on 2024-01-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_eicrole_eorole_remove_eicuserprofile_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='status',
            field=models.CharField(default='', max_length=256),
        ),
    ]
