# Generated by Django 4.1.7 on 2024-01-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_system_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='password',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
