# Generated by Django 4.1.7 on 2024-03-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_system_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='systems',
            field=models.ManyToManyField(blank=True, to='manager.system'),
        ),
    ]
